overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  devalue@>=5.1.0 <5.6.2: '>=5.6.2'
  devalue@>=5.3.0 <=5.6.1: '>=5.6.2'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  eslint@<9.26.0: '>=9.26.0'
  h3@<=1.15.4: '>=1.15.5'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  node-forge@<1.3.2: '>=1.3.2'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
